export const SAMPLE_RATE = 16000;
export const SPEECH_THRESHOLD = 0.5;
export const EXIT_THRESHOLD = 0.25;
export const MAX_BUFFER_DURATION = 30;
export const SPEECH_PAD_SAMPLES = 1600;
export const MIN_SILENCE_DURATION_SAMPLES = 8000;
export const MIN_SPEECH_DURATION_SAMPLES = 4000;
export const MAX_NUM_PREV_BUFFERS = 4;