import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    },
    {
      type: 'category',
      label: 'Prompt Library',
      items: [
        'prompt-library/index',
        {
          type: 'category',
          label: 'Prompts',
          items: [{type: 'autogenerated', dirName: 'prompt-library/prompts'}],
        },
        {
          type: 'category',
          label: 'Goose Hints',
          items: [{type: 'autogenerated', dirName: 'prompt-library/goosehints'}],
        },
      ],
    },
  ],
};

export default sidebars;